# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_details.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62ook_details.proto\"\xab\x01\n\x04\x42ook\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x06\x61uthor\x18\x03 \x01(\x0b\x32\x07.AuthorH\x02\x88\x01\x01\x12\x1a\n\x05genre\x18\x04 \x01(\x0e\x32\x06.GenreH\x03\x88\x01\x01\x12\x11\n\x04year\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x07\n\x05_ISBNB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x07\n\x05_year\"(\n\x06\x41uthor\x12\x13\n\x06\x61uthor\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_author\"\x8a\x01\n\rInventoryItem\x12\x1c\n\x0finventoryNumber\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x1c\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusH\x02\x88\x01\x01\x42\x07\n\x05referB\x12\n\x10_inventoryNumberB\t\n\x07_status\"$\n\x10\x63reateBookOutput\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1c\n\x0cgetBookInput\x12\x0c\n\x04isbn\x18\x01 \x01(\t*G\n\x05Genre\x12\x0c\n\x08THRILLER\x10\x00\x12\x0b\n\x07MYSTERY\x10\x01\x12\n\n\x06\x43OMEDY\x10\x02\x12\n\n\x06HORROR\x10\x03\x12\x0b\n\x07ROMANCE\x10\x04*\"\n\x06Status\x12\r\n\tavailable\x10\x00\x12\t\n\x05taken\x10\x01\x32_\n\x10InventoryService\x12(\n\nCreateBook\x12\x05.Book\x1a\x11.createBookOutput\"\x00\x12!\n\x07GetBook\x12\r.getBookInput\x1a\x05.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_details_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=447
  _GENRE._serialized_end=518
  _STATUS._serialized_start=520
  _STATUS._serialized_end=554
  _BOOK._serialized_start=23
  _BOOK._serialized_end=194
  _AUTHOR._serialized_start=196
  _AUTHOR._serialized_end=236
  _INVENTORYITEM._serialized_start=239
  _INVENTORYITEM._serialized_end=377
  _CREATEBOOKOUTPUT._serialized_start=379
  _CREATEBOOKOUTPUT._serialized_end=415
  _GETBOOKINPUT._serialized_start=417
  _GETBOOKINPUT._serialized_end=445
  _INVENTORYSERVICE._serialized_start=556
  _INVENTORYSERVICE._serialized_end=651
# @@protoc_insertion_point(module_scope)
